openapi: "3.0.0"
info:
  version: 1.0.0
  title: Config Server
servers:
  - url: http://localhost:8585
paths:
  /config/{application}:
    get:
      summary: "Obtener configuración"
      description: "Devuelve la configuración para una aplicación"
      operationId: getConfig
      tags:
        - "Configuraciones"
      parameters:
        - name: application
          in: path
          required: true
          description: "Devuelve configuracion"
          schema:
            type: string
            example: ""

